
const KEY='pbos_v3';
const LEGACY_KEY='pbos_iphone_v1';
const V2_KEY='pbos_v2';
const APP_VERSION='4.7.1';
const defaults={settings:{currency:'USD',startingCash:0,saveTarget:500,incomeGrowth:0,appearance:{theme:'classic',iconPreset:'outline',density:'comfortable',customAccent:''},sync:{url:'',key:'',email:''},updates:{auto:true,lastChecked:''}},categories:['Housing','Utilities','Groceries','Dining','Transportation','Fuel','Insurance','Subscriptions','Entertainment','Shopping','Healthcare','Personal','Travel','Education','Debt Payment','Savings','Investments','Other'],incomes:[],transactions:[],bills:[],billOccurrences:[],paychecks:[],assignments:[],budgets:[],debts:[],goals:[],assets:[],liabilities:[],investments:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null');
if(!db){
  const legacy=localStorage.getItem(LEGACY_KEY)||localStorage.getItem(V2_KEY);
  db=legacy?JSON.parse(legacy):structuredClone(defaults);
}
db.settings={...structuredClone(defaults.settings),...(db.settings||{})};
db.settings.appearance={...structuredClone(defaults.settings.appearance),...(db.settings.appearance||{})};
db.settings.sync={...structuredClone(defaults.settings.sync),...(db.settings.sync||{})};
db.settings.updates={...structuredClone(defaults.settings.updates),...(db.settings.updates||{})};
db.categories=db.categories||structuredClone(defaults.categories);
const today=new Date(), localDateKey=d=>{let y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}, currentMonth=()=>{let y=today.getFullYear(),m=String(today.getMonth()+1).padStart(2,'0');return `${y}-${m}`};
db.billOccurrences=Array.isArray(db.billOccurrences)?db.billOccurrences:[];
function migrateBills(){
  db.bills=(db.bills||[]).map(b=>{
    if(!b.id)b.id='bill-'+Date.now().toString(36)+Math.random().toString(36).slice(2,7);
    if(!b.billType)b.billType=b.frequency==='one-time'?'one-time':'recurring';
    if(!b.amountType)b.amountType='fixed';
    if(b.expectedAmount==null)b.expectedAmount=+b.amount||0;
    if(!b.startDate){let day=Math.min(Math.max(+b.dueDay||1,1),28);b.startDate=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;}
    if(b.active==null)b.active=true;
    if(b.autopay==null)b.autopay=false;
    return b;
  });
}
migrateBills();

['debts','goals','assets','liabilities','investments'].forEach(type=>{(db[type]||[]).forEach(item=>{if(!Array.isArray(item.history))item.history=[]})});
save();
function save(){localStorage.setItem(KEY,JSON.stringify(db)); window.dispatchEvent(new Event('pbos-data-changed'));}
const $=id=>document.getElementById(id), uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const iso=d=>{let x=new Date(d);return new Date(x.getTime()-x.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:db.settings.currency||'USD',maximumFractionDigits:2}).format(+n||0);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dateText=s=>new Date(s+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
const ICONS={
 home:'<svg viewBox="0 0 24 24"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/></svg>',
 activity:'<svg viewBox="0 0 24 24"><path d="M3 12h4l2-7 4 14 2-7h6"/></svg>',
 plan:'<svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h10M4 18h16"/></svg>',
 bills:'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 8h10M7 12h10M7 16h6"/></svg>',
 report:'<svg viewBox="0 0 24 24"><path d="M4 19V5M4 19h16"/><path d="m7 15 4-4 3 2 5-7"/></svg>',
 settings:'<svg viewBox="0 0 24 24"><path d="M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z"/><path d="m4.9 4.9 1.4 1.4M17.7 17.7l1.4 1.4M4 12H2M22 12h-2M12 4V2M12 22v-2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>'
};
const ICON_PRESETS={outline:{name:'Outline',desc:'Clean line icons'},rounded:{name:'Rounded',desc:'Softer, friendly shapes'},bold:{name:'Bold',desc:'Stronger visual weight'},minimal:{name:'Minimal',desc:'Simple symbols'}};
const THEME_ACCENTS={classic:'#2563eb',noir:'#242424',nightfall:'#72e06a',ko:'#6f7f4f',aura:'#6b5cff',ledger:'#315c4b',prism:'#6c4df6',evergreen:'#28724d',ocean:'#167c9a',raw:'#0b0b0b'};
const THEMES={classic:{name:'Classic',desc:'Clean professional finance',sw:['#f4f6f8','#ffffff','#2563eb']},noir:{name:'Noir',desc:'Monochrome editorial',sw:['#f4f4f2','#ffffff','#242424']},nightfall:{name:'Nightfall',desc:'Premium dark fintech',sw:['#0b0e12','#141820','#72e06a']},ko:{name:'Kō',desc:'Japanese minimal',sw:['#f7f4ed','#fffdf8','#6f7f4f']},aura:{name:'Aura',desc:'Glass and soft gradients',sw:['#eef1f8','#ffffff','#6b5cff']},ledger:{name:'Ledger',desc:'Paper and editorial',sw:['#f3eee3','#fbf8f0','#315c4b']},prism:{name:'Prism',desc:'Colorful and energetic',sw:['#f6f7fb','#ffffff','#6c4df6']},evergreen:{name:'Evergreen',desc:'Calm wealth aesthetic',sw:['#f1f5f1','#ffffff','#28724d']},ocean:{name:'Ocean',desc:'Cool modern finance',sw:['#eef5f7','#ffffff','#167c9a']},raw:{name:'Raw',desc:'Bold brutalist interface',sw:['#f7f7f7','#ffffff','#0b0b0b']}};
function applyAppearance(){let a=db.settings.appearance||defaults.settings.appearance;let theme=a.theme||'classic';document.documentElement.dataset.theme=theme;document.documentElement.dataset.density=a.density||'comfortable';document.documentElement.dataset.iconPreset=a.iconPreset||'outline';if(a.customAccent)document.documentElement.style.setProperty('--accent',a.customAccent);else document.documentElement.style.setProperty('--accent',THEME_ACCENTS[theme]||THEME_ACCENTS.classic);document.querySelectorAll('[data-icon]').forEach(el=>{let key=el.dataset.icon;el.innerHTML=ICONS[key]||'';if(a.iconPreset==='bold')el.style.transform='scale(1.08)';else el.style.transform='';});if($('themeStatus'))$('themeStatus').textContent=THEMES[a.theme||'classic']?.name||'Classic';}
let accentTouched=false;
function renderAppearanceSettings(){let a=db.settings.appearance||defaults.settings.appearance;if($('density'))$('density').value=a.density||'comfortable';if($('customAccent'))$('customAccent').value=a.customAccent||THEME_ACCENTS[a.theme||'classic']||THEME_ACCENTS.classic;if($('themeChoices'))$('themeChoices').innerHTML=Object.entries(THEMES).map(([k,t])=>`<button class="choice ${a.theme===k?'selected':''}" data-theme-choice="${k}"><div class="themeSwatches">${t.sw.map(c=>`<i style="background:${c}"></i>`).join('')}</div><strong>${t.name}</strong><small>${t.desc}</small></button>`).join('');if($('iconChoices'))$('iconChoices').innerHTML=Object.entries(ICON_PRESETS).map(([k,v])=>`<button class="choice ${a.iconPreset===k?'selected':''}" data-icon-choice="${k}"><span class="navIcon" data-icon="home" style="margin-bottom:7px"></span><strong>${v.name}</strong><small>${v.desc}</small></button>`).join('');document.querySelectorAll('[data-theme-choice]').forEach(b=>b.onclick=()=>{db.settings.appearance.theme=b.dataset.themeChoice;db.settings.appearance.customAccent='';accentTouched=false;save();applyAppearance();renderAppearanceSettings();});if($('customAccent'))$('customAccent').oninput=()=>{accentTouched=true;db.settings.appearance.customAccent=$('customAccent').value;applyAppearance();};document.querySelectorAll('[data-icon-choice]').forEach(b=>b.onclick=()=>{db.settings.appearance.iconPreset=b.dataset.iconChoice;save();applyAppearance();renderAppearanceSettings();});}
applyAppearance();

function nav(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('#nav button,#mobileNav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));render();scrollTo(0,0)}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>nav(b.dataset.page));
document.querySelectorAll('#mobileNav button').forEach(b=>b.onclick=()=>nav(b.dataset.page));
$('quickAdd').onclick=()=>openModal('transaction');

$('menuBtn').onclick=()=>{let side=document.querySelector('.side');let hidden=getComputedStyle(side).display==='none'||side.dataset.closed==='1';side.dataset.closed=hidden?'0':'1';side.style.display=hidden?'block':'none';if(hidden){side.style.position='fixed';side.style.zIndex=20;}};
$('monthPill').textContent=today.toLocaleDateString(undefined,{month:'long',year:'numeric'});
$('addBtn').onclick=()=>openModal('transaction');

function monthlyIncome(){return db.incomes.reduce((s,x)=>{let a=+x.amount||0;return s+(x.frequency==='weekly'?a*52/12:x.frequency==='biweekly'?a*26/12:x.frequency==='annual'?a/12:a)},0)}
function parseDateParts(v){let [y,m,d]=String(v||'').split('-').map(Number);return Number.isFinite(y)&&Number.isFinite(m)&&Number.isFinite(d)?new Date(y,m-1,d):null}
function dateISO(y,m,d){let x=new Date(y,m-1,d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}
function addMonthsISO(dateStr,n){let d=parseDateParts(dateStr);if(!d)return '';let day=d.getDate(),x=new Date(d.getFullYear(),d.getMonth()+n,1),last=new Date(x.getFullYear(),x.getMonth()+1,0).getDate();return dateISO(x.getFullYear(),x.getMonth()+1,Math.min(day,last))}
function addDaysISO(dateStr,n){let d=parseDateParts(dateStr);if(!d)return '';d.setDate(d.getDate()+n);return dateISO(d.getFullYear(),d.getMonth()+1,d.getDate())}
function billStep(b){return b.frequency==='weekly'?{days:7}:b.frequency==='biweekly'?{days:14}:b.frequency==='monthly'?{months:1}:b.frequency==='quarterly'?{months:3}:b.frequency==='semiannual'?{months:6}:b.frequency==='annual'?{months:12}:{months:1}}
function nextOccurrenceDate(b,from){let start=b.startDate;if(!start)return null;let cur=start, guard=0, target=from||localDateKey(today), step=billStep(b);while(cur<target&&guard++<240){cur=step.days?addDaysISO(cur,step.days):addMonthsISO(cur,step.months)}return cur}
function occurrenceStatus(o){if(o.payments?.length||o.transactionId)return 'paid';let todayKey=localDateKey(today);if(o.dueDate<todayKey)return 'overdue';if(o.dueDate===todayKey)return 'due';return 'upcoming'}
function ensureBillOccurrences(){
  db.billOccurrences=db.billOccurrences||[];
  const existing=new Set(db.billOccurrences.map(o=>o.id));
  const min=addMonthsISO(localDateKey(today),-12), max=addMonthsISO(localDateKey(today),18);
  db.bills.forEach(b=>{if(!b.active)return;let cur=b.startDate;if(!cur)return;let guard=0,step=billStep(b);while(cur<=max&&guard++<240){if(cur>=min){let id=`bo-${b.id}-${cur}`;if(!existing.has(id)){db.billOccurrences.push({id,billId:b.id,dueDate:cur,expectedAmount:+b.expectedAmount||+b.amount||0,status:'upcoming',paidDate:null,actualAmount:null,payments:[],transactionId:null});existing.add(id)}}if(b.billType==='one-time')break;cur=step.days?addDaysISO(cur,step.days):addMonthsISO(cur,step.months)}});
  db.billOccurrences.forEach(o=>{let b=db.bills.find(x=>x.id===o.billId);if(b){o.expectedAmount=o.expectedAmount==null?(+b.expectedAmount||+b.amount||0):o.expectedAmount;o.status=occurrenceStatus(o)}});
}
function getOccurrence(id){return db.billOccurrences.find(o=>o.id===id)}
function getBill(id){return db.bills.find(b=>b.id===id)}
function occurrencePayments(o){let ids=o.payments?.length?o.payments:(o.transactionId?[o.transactionId]:[]);return ids.map(id=>db.transactions.find(t=>t.id===id)).filter(Boolean)}
function occurrencePaidAmount(o){return occurrencePayments(o).reduce((s,t)=>s+(+t.amount||0),0)}
function occurrenceDisplayStatus(o){let paid=occurrencePaidAmount(o);if(paid>0&&paid<(+o.expectedAmount||0))return 'partial';return paid>=0&&paid>=(+o.expectedAmount||0)&&paid>0?'paid':occurrenceStatus(o)}
function unpaidOccurrencesForRange(start,end){ensureBillOccurrences();return db.billOccurrences.filter(o=>o.dueDate>=start&&o.dueDate<=end&&occurrenceDisplayStatus(o)!=='paid')}
function upcomingBillOccurrences(limit=10){ensureBillOccurrences();let key=localDateKey(today);return db.billOccurrences.filter(o=>o.dueDate>=key&&occurrenceDisplayStatus(o)!=='paid').sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,limit)}
function monthlyBillTotalFor(key){let start=`${key}-01`,end=dateISO(+key.slice(0,4),+key.slice(5),new Date(+key.slice(0,4),+key.slice(5),0).getDate());return unpaidOccurrencesForRange(start,end).reduce((s,o)=>s+(+o.expectedAmount||0),0)}
function monthlyRecurringBills(){ensureBillOccurrences();let y=today.getFullYear(),m=today.getMonth()+1,start=`${y}-${String(m).padStart(2,'0')}-01`,end=dateISO(y,m,new Date(y,m,0).getDate());return db.billOccurrences.filter(o=>o.dueDate>=start&&o.dueDate<=end&&occurrenceDisplayStatus(o)!=='paid').reduce((s,o)=>s+(+o.expectedAmount||0),0)}
function dashboardOutflowsFor(key){
  const transactions=db.transactions
    .filter(x=>x.type==='expense'&&String(x.date||'').startsWith(key))
    .map(t=>{
      const occ=t.billOccurrenceId?getOccurrence(t.billOccurrenceId):null;
      const bill=occ?getBill(occ.billId):null;
      return {id:`tx-${t.id}`,txId:t.id,kind:bill?'billPayment':'transaction',name:t.payee||t.note||t.category||'Expense',category:t.category||bill?.category||'Other',amount:+t.amount||0,date:t.date,frequency:'transaction',billOccurrenceId:t.billOccurrenceId||null,billName:bill?.name||null};
    });
  return {transactions,allTransactions:transactions,bills:transactions.filter(x=>x.kind==='billPayment'),billOutflows:transactions.filter(x=>x.kind==='billPayment'),entries:transactions};
}
function txTotal(type,m=null){return db.transactions.filter(x=>x.type===type&&(!m||String(x.date||'').startsWith(m))).reduce((s,x)=>s+(+x.amount||0),0)}
function monthKeyFromDate(d){let y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0');return `${y}-${m}`}
function monthlyIncomeFor(key){return monthlyIncome()+txTotal('income',key)}
function monthlyExpenseFor(key){return dashboardOutflowsFor(key).transactions.filter(x=>x.kind!=='billPayment').reduce((s,x)=>s+(+x.amount||0),0)}
function monthlyBillFor(key){return dashboardOutflowsFor(key).transactions.filter(x=>x.kind==='billPayment').reduce((s,x)=>s+(+x.amount||0),0)}
function monthlySpendingFor(key){return monthlyExpenseFor(key)+monthlyBillFor(key)}
function monthlyAvailableFor(key){return monthlyIncomeFor(key)-monthlySpendingFor(key)}
function cashPositionHistory(){let arr=[],d=new Date(today.getFullYear(),today.getMonth()-11,1);for(let i=0;i<12;i++){let key=monthKeyFromDate(d),available=monthlyAvailableFor(key);arr.push({key,available,inc:monthlyIncomeFor(key),spent:monthlyExpenseFor(key),bills:monthlyBillFor(key)});d.setMonth(d.getMonth()+1)}return arr}
function forecast(){let arr=[],cash=+db.settings.startingCash||0,d=new Date(today.getFullYear(),today.getMonth(),1),growth=(+db.settings.incomeGrowth||0)/100;for(let i=0;i<12;i++){let key=monthKeyFromDate(d),inc=monthlyIncome()*Math.pow(1+growth,i/12)+txTotal('income',key),b=monthlyBillTotalFor(key),sp=monthlyBudget(),debt=debtPayments(),gi=goalsInvestMonthly(),net=inc-b-sp-debt-gi;cash+=net;arr.push({key,inc,b,sp,debt,gi,net,cash});d.setMonth(d.getMonth()+1)}return arr}

function canvas(id,mode,data){
  let c=$(id); if(!c)return;
  let w=Math.max(300,c.clientWidth||500),h=245,dpr=devicePixelRatio||1;
  c.width=w*dpr;c.height=h*dpr;
  let x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);x.font='12px system-ui';x.fillStyle='#667085';
  if(!data.length){x.fillText('No data yet',20,30);return}
  let pad={l:36,r:14,t:16,b:30},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b;
  let vals=data.map(v=>Number(v.v??0)),max=Math.max(...vals,0),min=Math.min(...vals,0);
  if(mode!=='line'){max=Math.max(...data.map(v=>Math.max(v.v||0,v.a||0,v.b||0)),1);min=0}
  let range=Math.max(max-min,1),yFor=v=>pad.t+ph*(1-(v-min)/range),zero=yFor(0);
  x.strokeStyle='#eaecf0';
  for(let i=0;i<4;i++){let yy=pad.t+ph*i/3;x.beginPath();x.moveTo(pad.l,yy);x.lineTo(w-pad.r,yy);x.stroke()}
  if(mode==='line'){
    x.strokeStyle='#2563eb';x.lineWidth=2;x.beginPath();
    data.forEach((p,i)=>{let xx=pad.l+pw*(i/(data.length-1||1)),yy=yFor(Number(p.v)||0);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke();
    data.forEach((p,i)=>{let xx=pad.l+pw*(i/(data.length-1||1)),yy=yFor(Number(p.v)||0);x.fillStyle='#2563eb';x.beginPath();x.arc(xx,yy,4,0,7);x.fill();if(i%2===0){x.fillStyle='#667085';x.fillText(p.l,xx-13,h-9)}});
    if(min<0&&max>0){x.strokeStyle='#98a2b3';x.setLineDash([4,4]);x.beginPath();x.moveTo(pad.l,zero);x.lineTo(w-pad.r,zero);x.stroke();x.setLineDash([])}
    if(id==='dashCash'){
      c._chartData=data;c._chartMeta={pad,pw,ph,yFor,w,h};let tip=$('cashTip');
      c.onmousemove=e=>showCashTip(e,c,tip);c.onclick=e=>showCashTip(e,c,tip,true);c.onmouseleave=()=>{if(tip)tip.style.display='none'};
    }
  }else if(mode==='bars'){
    let bw=pw/data.length*.7;
    data.forEach((p,i)=>{let xx=pad.l+pw*(i+.5)/data.length,ha=ph*(p.a||0)/max,hb=ph*(p.b||0)/max;x.fillStyle='#2563eb';x.fillRect(xx-bw/2,pad.t+ph-ha,bw/2-2,ha);x.fillStyle='#98a2b3';x.fillRect(xx+2,pad.t+ph-hb,bw/2-2,hb);x.fillStyle='#667085';x.fillText(p.l,xx-10,h-9)});
  }else if(mode==='pie'){
    let total=data.reduce((s,p)=>s+(+p.v||0),0),st=-Math.PI/2;
    data.forEach((p,i)=>{let a=total?(p.v/total)*Math.PI*2:0;x.fillStyle=['#2563eb','#7f56d9','#12b76a','#f79009','#ef6820','#667085'][i%6];x.beginPath();x.moveTo(w/2,h/2);x.arc(w/2,h/2,78,st,st+a);x.closePath();x.fill();st+=a});
    if(id==='dashSpend'){
      c._chartData=data;c._chartMeta={w,h};let tip=$('spendTip');
      c.onmousemove=e=>showSpendTip(e,c,tip,false);c.onclick=e=>showSpendTip(e,c,tip,true);
      c.ontouchend=e=>{let t=e.changedTouches?.[0];if(t)showSpendTip({clientX:t.clientX,clientY:t.clientY},c,tip,true)};
      c.onmouseleave=()=>{if(tip)tip.style.display='none'};
    }
  }
}
function showCashTip(e,c,tip,keep){if(!tip||!c._chartData)return;let r=c.getBoundingClientRect(),mx=e.clientX-r.left,meta=c._chartMeta,idx=Math.max(0,Math.min(c._chartData.length-1,Math.round((mx-meta.pad.l)/meta.pw*(c._chartData.length-1))));let p=c._chartData[idx];let rows=`<strong>${esc(p.label||p.key)}</strong><div class="tiprow"><span>Income</span><b>${money(p.inc)}</b></div><div class="tiprow"><span>Expenses</span><b>${money(p.spent)}</b></div><div class="tiprow"><span>Bills</span><b>${money(p.bills)}</b></div><div class="tiprow tipsave"><span>${p.available>=0?'Saved':'Shortfall'}</span><b class="${p.available>=0?'good':'bad'}">${p.available>=0?'+':''}${money(p.available)}</b></div>`;tip.innerHTML=rows;let xx=meta.pad.l+meta.pw*(idx/(c._chartData.length-1||1));tip.style.display='block';tip.style.left=Math.max(6,Math.min(meta.w-186,xx-90))+'px';tip.style.top=Math.max(6,meta.yFor(p.available)-65)+'px';if(!keep)tip._hover=true}
function showSpendTip(e,c,tip,keep){if(!tip||!c._chartData?.length)return;let r=c.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,cx=c.clientWidth/2,cy=c.clientHeight/2,dx=mx-cx,dy=my-cy,dist=Math.sqrt(dx*dx+dy*dy);if(dist>82||dist<24){if(!keep)tip.style.display='none';return}let angle=Math.atan2(dy,dx)+Math.PI/2;if(angle<0)angle+=Math.PI*2;let total=c._chartData.reduce((s,p)=>s+(+p.v||0),0),cursor=0,idx=-1;for(let i=0;i<c._chartData.length;i++){let sweep=total?(c._chartData[i].v/total)*Math.PI*2:0;if(angle>=cursor&&angle<cursor+sweep){idx=i;break}cursor+=sweep}if(idx<0)return;let p=c._chartData[idx],pct=total?(p.v/total)*100:0;tip.innerHTML=`<strong>${esc(p.l)}</strong><div class="tiprow"><span>Total</span><b>${money(p.v)}</b></div><div class="tiprow"><span>Share of spending</span><b>${pct.toFixed(1)}%</b></div>`;tip.style.display='block';tip.style.left=Math.max(6,Math.min(c.clientWidth-180,mx+12))+'px';tip.style.top=Math.max(6,Math.min(c.clientHeight-78,my-12))+'px';tip._selected=keep?idx:null}

function comparisonPct(current,previous){if(previous===null||previous===undefined||!Number.isFinite(previous)||Math.abs(previous)<0.000001)return null;if(!Number.isFinite(current))return null;if(current!==0&&previous!==0&&((current<0)!=(previous<0)))return null;return (current-previous)/Math.abs(previous)*100}
function monthOffsetKey(offset){let d=new Date(today.getFullYear(),today.getMonth()+offset,1);return monthKeyFromDate(d)}
function quarterValue(monthsBack,metric){let end=new Date(today.getFullYear(),today.getMonth()-monthsBack,1),start=new Date(end.getFullYear(),end.getMonth()-2,1),sum=0;for(let i=0;i<3;i++){let k=monthKeyFromDate(new Date(start.getFullYear(),start.getMonth()+i,1));sum+=metric(k)}return sum}
function currentSnapshot(){let assets=db.assets.reduce((s,x)=>s+(+x.value||0),0),debt=db.debts.reduce((s,x)=>s+(+x.balance||0),0)+db.liabilities.reduce((s,x)=>s+(+x.value||0),0),invest=db.investments.reduce((s,x)=>s+(+x.balance||0),0),savings=db.goals.reduce((s,x)=>s+(+x.saved||0),0);return{net:assets+invest-debt,debt,invest,savings}}
function historyValueAt(record,asOf){let h=Array.isArray(record.history)?record.history.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))):[];let hit=h.filter(x=>String(x.date||'')<=asOf).pop();return hit&&Number.isFinite(+hit.value)?+hit.value:null}
function aggregateHistoryAt(collection,field,asOf){let total=0;for(const item of collection){if(item.createdAt&&String(item.createdAt)>asOf)continue;let v=historyValueAt(item,asOf);if(v===null)return null;total+=v}return total}
function historicalSnapshotAt(asOf){let assets=aggregateHistoryAt(db.assets,'value',asOf),invest=aggregateHistoryAt(db.investments,'balance',asOf),liabilities=aggregateHistoryAt(db.liabilities,'value',asOf),debts=aggregateHistoryAt(db.debts,'balance',asOf),savings=aggregateHistoryAt(db.goals,'saved',asOf);if([assets,invest,liabilities,debts,savings].some(v=>v===null))return null;return{net:assets+invest-liabilities-debts,debt:liabilities+debts,invest,savings}}
function periodEnd(kind){if(kind==='month')return localDateKey(new Date(today.getFullYear(),today.getMonth(),0));if(kind==='quarter'){let qStart=Math.floor(today.getMonth()/3)*3;return localDateKey(new Date(today.getFullYear(),qStart,0));}return `${today.getFullYear()-1}-12-31`}
function historicalBalanceChanges(now){let periods={month:historicalSnapshotAt(periodEnd('month')),quarter:historicalSnapshotAt(periodEnd('quarter')),year:historicalSnapshotAt(periodEnd('year'))};let keys=['net','debt','invest','savings'];return Object.fromEntries(keys.map(k=>[k,{month:periods.month?balanceChange(now[k],periods.month[k]):null,quarter:periods.quarter?balanceChange(now[k],periods.quarter[k]):null,year:periods.year?balanceChange(now[k],periods.year[k]):null}]))}
function periodFlowTotals(offsetMonths){let end=new Date(today.getFullYear(),today.getMonth()+offsetMonths,1),start=new Date(end.getFullYear(),end.getMonth()-2,1),income=0,spend=0,saved=0;for(let i=0;i<3;i++){let k=monthKeyFromDate(new Date(start.getFullYear(),start.getMonth()+i,1));income+=monthlyIncomeFor(k);spend+=monthlySpendingFor(k);saved+=monthlyAvailableFor(k)}return{income,spend,saved}}
function yearFlowTotals(offsetYears){let y=today.getFullYear()+offsetYears,income=0,spend=0,saved=0;for(let i=0;i<12;i++){let k=`${y}-${String(i+1).padStart(2,'0')}`;income+=monthlyIncomeFor(k);spend+=monthlySpendingFor(k);saved+=monthlyAvailableFor(k)}return{income,spend,saved}}
function changeText(v){if(v===null||v===undefined||!Number.isFinite(v))return '-';if(Math.abs(v)<0.00005)return '→ 0.0%';return v>0?`↑ ${Math.abs(v).toFixed(1)}%`:`↓ ${Math.abs(v).toFixed(1)}%`}
function changeClass(v){if(v===null||v===undefined||!Number.isFinite(v))return 'neutral';return v>0?'changeUp':v<0?'changeDown':'changeFlat'}
function balanceChange(current,previous){if(previous===null||previous===undefined||!Number.isFinite(previous)||!Number.isFinite(current))return null;return current-previous}
function balanceChangeText(v){if(v===null||v===undefined||!Number.isFinite(v))return '-';if(Math.abs(v)<0.005)return '→ $0.00';return v>0?`↑ ${money(Math.abs(v))}`:`↓ ${money(Math.abs(v))}`}
function balanceChangePeriodText(v){if(v===null||v===undefined||!Number.isFinite(v))return '-';if(Math.abs(v)<0.005)return '→ $0.00';return v>0?`↑ ${money(Math.abs(v))}`:`↓ ${money(Math.abs(v))}`}
function snapshotMetrics(){let now=currentSnapshot(),m=currentMonth(),qNow=periodFlowTotals(0),qPrev=periodFlowTotals(-3),yNow=yearFlowTotals(0),yPrev=yearFlowTotals(-1),bc=historicalBalanceChanges(now);return{month:{...now,available:monthlyAvailableFor(m),income:monthlyIncomeFor(m),spend:monthlySpendingFor(m)},balanceChanges:{net:bc.net.month,debt:bc.debt.month,invest:bc.invest.month,savings:bc.savings.month},balanceQuarter:{net:bc.net.quarter,debt:bc.debt.quarter,invest:bc.invest.quarter,savings:bc.savings.quarter},balanceYear:{net:bc.net.year,debt:bc.debt.year,invest:bc.invest.year,savings:bc.savings.year},changes:{savings:comparisonPct(monthlyAvailableFor(m),monthlyAvailableFor(monthOffsetKey(-1))),income:comparisonPct(monthlyIncomeFor(m),monthlyIncomeFor(monthOffsetKey(-1))),spend:comparisonPct(monthlySpendingFor(m),monthlySpendingFor(monthOffsetKey(-1)))},quarter:{savings:comparisonPct(qNow.saved,qPrev.saved),income:comparisonPct(qNow.income,qPrev.income),spend:comparisonPct(qNow.spend,qPrev.spend)},year:{savings:comparisonPct(yNow.saved,yPrev.saved),income:comparisonPct(yNow.income,yPrev.income),spend:comparisonPct(yNow.spend,yPrev.spend)}}}

function renderDashboard(){let m=currentMonth(),incomeTransactions=db.transactions.filter(x=>x.type==='income'&&String(x.date||'').startsWith(m)),out=dashboardOutflowsFor(m),inc=monthlyIncome()+incomeTransactions.reduce((s,x)=>s+(+x.amount||0),0),spent=out.transactions.reduce((s,x)=>s+x.amount,0),plannedBills=monthlyBillTotalFor(m),avail=inc-spent;$('dashCards').innerHTML=[['Income',money(inc),''],['Spending',money(spent),spent>0?'':''],['Bills',money(plannedBills),''],['Available',money(avail),avail>=0?'good':'bad']].map(a=>`<div class="card"><div class="label">${a[0]}</div><div class="metric ${a[2]}">${a[1]}</div>${a[0]==='Bills'?'<div class="mini">unpaid bill obligations</div>':''}</div>`).join('');let cp=cashPositionHistory().map(x=>({...x,l:x.key.slice(5),v:x.available,label:new Date(x.key+'-01T12:00:00').toLocaleDateString(undefined,{month:'long',year:'numeric'})}));canvas('dashCash','line',cp);let cats={};out.entries.forEach(item=>{let k=item.category||'Other';cats[k]=(cats[k]||0)+item.amount});canvas('dashSpend','pie',Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,7).map(x=>({l:x[0],v:x[1]})));$('expenseCount').textContent=`(${out.entries.length})`;$('expenseTotal').textContent=money(spent);$('expenseList').innerHTML=out.transactions.length?out.transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(item=>`<div class="listrow"><span>${esc(item.name)}<br><span class="mini">${dateText(item.date)} · ${esc(item.category)}${item.billOccurrenceId?' · Bill payment':''}</span></span><b>${money(item.amount)}</b></div>`).join(''):'<div class="empty" style="padding:14px">No expenses recorded for this month.</div>';let next=upcomingBillOccurrences(6);
  $('dashBills').innerHTML=next.map(o=>{
    let b=getBill(o.billId),st=occurrenceDisplayStatus(o);
    return `<div class="listrow"><button type="button" class="billDashLink" onclick="showBillOccurrence('${o.id}')"><span><b>${esc(b?.name||'Bill')}</b><br><span class="mini">Due ${dateText(o.dueDate)} · ${billStatusHtml(st)}</span></span></button><b>${money(o.expectedAmount)}</b></div>`;
  }).join('')||'<div class="empty">No unpaid upcoming bills. Add a bill or check Bills &amp; Calendar.</div>';let s=snapshotMetrics(),balanceMetrics=[['Net worth',s.month.net,s.balanceChanges.net,s.balanceQuarter.net,s.balanceYear.net],['Debt balance',s.month.debt,s.balanceChanges.debt,s.balanceQuarter.debt,s.balanceYear.debt],['Investment balance',s.month.invest,s.balanceChanges.invest,s.balanceQuarter.invest,s.balanceYear.invest],['Savings',s.month.savings,s.balanceChanges.savings,s.balanceQuarter.savings,s.balanceYear.savings]],flowMetrics=[['Available',s.month.available,s.changes.savings,s.quarter.savings,s.year.savings],['Income',s.month.income,s.changes.income,s.quarter.income,s.year.income],['Spending',s.month.spend,s.changes.spend,s.quarter.spend,s.year.spend]],balanceCard=x=>`<div class="snapshotMetric balanceMetric"><div class="label">${x[0]}</div><div class="metric ${x[1]<0?'bad':''}">${money(x[1])}</div><div class="snapshotChanges"><span><b>Last Month</b><strong class="${changeClass(x[2])}">${balanceChangeText(x[2])}</strong></span><span><b>Last Quarter</b><strong class="${changeClass(x[3])}">${balanceChangePeriodText(x[3])}</strong></span><span><b>Last Year</b><strong class="${changeClass(x[4])}">${balanceChangePeriodText(x[4])}</strong></span></div></div>`,flowCard=x=>`<div class="snapshotMetric flowMetric"><div class="label">${x[0]}</div><div class="metric ${x[1]<0?'bad':''}">${money(x[1])}</div><div class="snapshotChanges"><span><b>Last Month</b><strong class="${changeClass(x[2])}">${changeText(x[2])}</strong></span><span><b>Last Quarter</b><strong class="${changeClass(x[3])}">${changeText(x[3])}</strong></span><span><b>Last Year</b><strong class="${changeClass(x[4])}">${changeText(x[4])}</strong></span></div></div>`;$('dashSnapshot').innerHTML=`<div class="snapshotSectionTitle">Balance Metrics</div><div class="snapshotHint">Current financial position · historical movement from source modules</div><div class="snapshotGrid">${balanceMetrics.map(balanceCard).join('')}</div><div class="snapshotSectionTitle">Flow Metrics</div><div class="snapshotHint">Financial activity · percentage change by period</div><div class="snapshotGrid">${flowMetrics.map(flowCard).join('')}</div>`}
function renderPlan(){let total=db.paychecks.reduce((s,p)=>s+ +p.amount,0),assigned=db.assignments.reduce((s,a)=>s+ +a.amount,0);$('planCards').innerHTML=[['Scheduled paychecks',money(total)],['Assigned',money(assigned)],['Unassigned',money(total-assigned)]].map(a=>`<div class="card"><div class="label">${a[0]}</div><div class="metric ${a[0]==='Unassigned'&&total-assigned<0?'bad':''}">${a[1]}</div></div>`).join('');$('paychecks').innerHTML=db.paychecks.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(p=>`<div class="listrow"><span><b>${fmtDate(p.date)}</b><br><span class="mini">${esc(p.name)}</span></span><b>${money(p.amount)}</b></div>`).join('')||'<div class="empty">Add your paychecks.</div>';$('allocation').innerHTML=`<div class="listrow"><span>Recurring bills</span><b>${money(monthlyRecurringBills())}</b></div><div class="listrow"><span>Debt payments</span><b>${money(debtPayments())}</b></div><div class="listrow"><span>Savings + investing</span><b>${money(goalsInvestMonthly())}</b></div><div class="listrow"><span>Category budget</span><b>${money(monthlyBudget())}</b></div>`;$('assignments').innerHTML=db.assignments.map(a=>{let p=db.paychecks.find(x=>x.id===a.paycheckId);return `<tr><td>${p?dateText(p.date):'Unknown'}</td><td>${esc(a.envelope)}</td><td>${money(a.amount)}</td><td>${esc(a.note)}</td><td><button class="btn small danger" onclick="remove('assignments','${a.id}')">Delete</button></td></tr>`}).join('')||'<tr><td colspan="5" class="empty">No assignments yet.</td></tr>'}
function renderTransactions(){
 ensureBillOccurrences();let q=($('txSearch').value||'').toLowerCase(),f=$('txFilter').value;
 let rows=db.transactions.filter(t=>(f==='all'||t.type===f)&&(String(t.payee||'')+' '+String(t.note||'')+' '+String(t.category||'')).toLowerCase().includes(q)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));
 $('txTable').innerHTML=rows.map(t=>{let bo=t.billOccurrenceId?getOccurrence(t.billOccurrenceId):null,b=bo?getBill(bo.billId):null;return `<tr><td>${dateText(t.date)}</td><td><b>${esc(t.payee||t.note||'')}</b><br><span class="mini">${esc(t.note||'')}</span></td><td><span class="pill">${esc(t.type)}</span></td><td>${esc(t.category||'')}</td><td>${esc(t.account||'')}</td><td class="${t.type==='income'?'good':t.type==='expense'?'bad':''}">${t.type==='income'?'+':t.type==='expense'?'-':''}${money(t.amount)}</td><td>${b?`<span class="pill">Bill: ${esc(b.name)}</span>`:'—'}</td><td><div class="billRowActions">${bo?`<button class="btn small" onclick="showBillOccurrence('${bo.id}')">View bill</button>`:''}<button class="btn small danger" onclick="deleteTransaction('${t.id}')">Delete</button></div></td></tr>`}).join('')||'<tr><td colspan="8" class="empty">No transactions.</td></tr>'}

let billCalendarDate=new Date(today.getFullYear(),today.getMonth(),1);
function billMonthKey(){return `${billCalendarDate.getFullYear()}-${String(billCalendarDate.getMonth()+1).padStart(2,'0')}`}
function changeBillMonth(delta){billCalendarDate.setMonth(billCalendarDate.getMonth()+delta);renderBills()}
function goBillToday(){billCalendarDate=new Date(today.getFullYear(),today.getMonth(),1);renderBills()}
function billStatusHtml(status){let label={paid:'Paid',partial:'Partially Paid',overdue:'Overdue',due:'Due',upcoming:'Upcoming'}[status]||status;return `<span class="billStatus ${status}">${label}</span>`}
function showBillOccurrence(id){ensureBillOccurrences();let o=getOccurrence(id),b=o&&getBill(o.billId);if(!o||!b)return;let status=occurrenceDisplayStatus(o),payments=occurrencePayments(o),paid=occurrencePaidAmount(o);$('billDetailsPanel').style.display='block';$('billDetailsPanel').innerHTML=`<div class="sectionhead"><div><h2>${esc(b.name)}</h2><div class="mini">${esc(b.category)} · ${esc(b.billType)} · ${esc(b.amountType)} amount</div></div><button class="btn small" onclick="$('billDetailsPanel').style.display='none'">Close</button></div><div class="billDetailHero"><div><div class="label">Due date</div><div><b>${dateText(o.dueDate)}</b></div><div class="mini">Expected ${money(o.expectedAmount)} · Paid ${money(paid)}</div></div><div style="text-align:right">${billStatusHtml(status)}<div class="billDetailAmount">${money((o.actualAmount??paid)||o.expectedAmount)}</div></div></div><div class="toolbar section"><button class="btn" onclick="openBillEdit('${b.id}')">Edit Bill</button>${status==='paid'?`<button class="btn" onclick="showBillTransaction('${payments[0]?.id||o.transactionId||''}')">View Transaction</button>`:`<button class="btn primary" onclick="openPaymentModal('${o.id}')">${status==='partial'?'Add Payment':'Mark Paid'}</button>`}</div>${payments.length?`<div class="section"><h3>Payment history</h3>${payments.map(t=>`<div class="billHistoryItem"><div class="listrow"><span><b>${dateText(t.date)}</b><br><span class="mini">${esc(t.account||'No account')} · ${esc(t.category||b.category)}</span></span><b>${money(t.amount)}</b></div></div>`).join('')}</div>`:''}`;window.scrollTo({top:document.getElementById('billDetailsPanel').offsetTop-80,behavior:'smooth'})}
function showBillTransaction(id){if(!id)return;let t=db.transactions.find(x=>x.id===id);if(!t)return;alert(`Transaction\n${dateText(t.date)} · ${t.payee||''}\n${money(t.amount)}\n${t.account||'No account'}`)}
function showBillDay(dateKey){
  ensureBillOccurrences();
  const items=db.billOccurrences.filter(o=>o.dueDate===dateKey).sort((a,b)=>String(a.id).localeCompare(String(b.id)));
  if(!items.length)return;
  $('modalTitle').textContent=`Bills for ${dateText(dateKey)}`;
  $('modalForm').innerHTML=`<div>${items.map(o=>{const b=getBill(o.billId),st=occurrenceDisplayStatus(o);return `<div class=\"listrow\"><button type=\"button\" class=\"billDashLink\" onclick=\"closeModal();showBillOccurrence('${o.id}')\"><span><b>${esc(b?.name||'Bill')}</b><br><span class=\"mini\">Expected ${money(o.expectedAmount)} · ${billStatusHtml(st)}</span></span></button>${st==='paid'?`<span>${money(occurrencePaidAmount(o))}</span>`:`<button type=\"button\" class=\"btn small primary\" onclick=\"closeModal();openPaymentModal('${o.id}')\">Mark Paid</button>`}</div>`}).join('')}</div>`;
  $('modalForm').dataset.type='dayDetail';
  $('modalBack').classList.add('show');
}

function renderBills(){
 ensureBillOccurrences();let key=billMonthKey(),[y,m]=key.split('-').map(Number),first=new Date(y,m-1,1),days=new Date(y,m,0).getDate(),start=first.getDay();$('calendarTitle').textContent=first.toLocaleDateString(undefined,{month:'long',year:'numeric'});
 let monthOcc=db.billOccurrences.filter(o=>o.dueDate.startsWith(key)).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
 let overdue=monthOcc.filter(o=>occurrenceDisplayStatus(o)==='overdue');let next7=(()=>{let e=addDaysISO(localDateKey(today),7);return db.billOccurrences.filter(o=>o.dueDate>=localDateKey(today)&&o.dueDate<=e&&occurrenceDisplayStatus(o)!=='paid')})();let paidThisMonth=db.billOccurrences.flatMap(occurrencePayments).filter(t=>t.date.startsWith(currentMonth())).reduce((s,t)=>s+(+t.amount||0),0);
 $('billSummaryCards').innerHTML=[['Upcoming',upcomingBillOccurrences().reduce((s,o)=>s+(+o.expectedAmount||0),0),'unpaid future obligations'],['Due Soon',next7.reduce((s,o)=>s+(+o.expectedAmount||0),0),'next 7 days'],['Overdue',db.billOccurrences.filter(o=>o.dueDate<localDateKey(today)&&occurrenceDisplayStatus(o)!=='paid').reduce((s,o)=>s+(+o.expectedAmount||0),0),'past-due obligations'],['Paid This Month',paidThisMonth,'actual bill payments']].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="metric">${money(x[1])}</div><div class="billSummaryNote">${x[2]}</div></div>`).join('');
 let cells=[];for(let i=0;i<start;i++)cells.push('<div class="day"></div>');for(let d=1;d<=days;d++){let ds=dateISO(y,m,d),os=monthOcc.filter(o=>o.dueDate===ds);cells.push(`<div class="day ${ds===localDateKey(today)?'today':''}"><button type="button" class="dayHeaderBtn" onclick="showBillDay('${ds}')"><span class="daynum">${d}</span>${os.length?`<span class="dayCount">${os.length}</span>`:''}</button>${os.map(o=>{let b=getBill(o.billId),st=occurrenceDisplayStatus(o);return `<button type="button" class="billEvent ${st}" onclick="event.stopPropagation();showBillOccurrence('${o.id}')"><span class="dot"></span><span>${esc(b?.name||'Bill')} · ${money(o.expectedAmount)}</span></button>`}).join('')}</div>`)}
 $('calendar').innerHTML=`<div class="calendarHead">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendarGrid">${cells.join('')}</div>`;
 $('overdueBillsSection').innerHTML=overdue.length?`<div class="sectionhead"><h2>Overdue Bills</h2><span class="mini">${overdue.length} occurrence${overdue.length===1?'':'s'}</span></div>${overdue.map(o=>{let b=getBill(o.billId);return `<div class="listrow"><span><b>${esc(b?.name||'Bill')}</b><br><span class="mini">Due ${dateText(o.dueDate)} · Expected ${money(o.expectedAmount)}</span></span><div class="billRowActions">${billStatusHtml('overdue')}<button class="btn small primary" onclick="openPaymentModal('${o.id}')">Mark Paid</button></div></div>`}).join('')}`:'';
 $('upcomingBills').innerHTML=upcomingBillOccurrences().map(o=>{let b=getBill(o.billId),st=occurrenceDisplayStatus(o);return `<div class="listrow"><span><b>${esc(b?.name||'Bill')}</b><br><span class="mini">${dateText(o.dueDate)} · Expected ${money(o.expectedAmount)}</span></span><div class="billRowActions">${billStatusHtml(st)}<button class="btn small primary" onclick="openPaymentModal('${o.id}')">Mark Paid</button></div></div>`}).join('')||'<div class="empty">No unpaid upcoming bills.</div>';
 $('activeBills').innerHTML=db.bills.filter(b=>b.active!==false).sort((a,b)=>String(a.name).localeCompare(String(b.name))).map(b=>{let next=db.billOccurrences.filter(o=>o.billId===b.id&&occurrenceDisplayStatus(o)!=='paid'&&o.dueDate>=localDateKey(today)).sort((a,c)=>a.dueDate.localeCompare(c.dueDate))[0];return `<div class="listrow"><span><b>${esc(b.name)}</b><br><span class="mini">${esc(b.category)} · ${esc(b.frequency)} · ${money(b.expectedAmount)}</span></span><div class="billRowActions"><button class="btn small" onclick="openBillEdit('${b.id}')">Edit</button>${next?`<button class="btn small" onclick="showBillOccurrence('${next.id}')">Details</button>`:''}<button class="btn small danger" onclick="deactivateBill('${b.id}')">Deactivate</button></div></div>`}).join('')||'<div class="empty">No active bills.</div>';
}
function openBillEdit(id){let b=getBill(id);if(!b)return;openModal('billEdit',b)}
function deactivateBill(id){let b=getBill(id);if(!b)return;if(confirm(`Deactivate ${b.name}? Future occurrences will stop, but payment history will remain.`)){b.active=false;save();ensureBillOccurrences();render()}}
function deleteBill(id){let b=getBill(id);if(!b)return;let hist=db.billOccurrences.some(o=>o.billId===id&&(occurrencePayments(o).length||o.dueDate<localDateKey(today)));if(hist){if(!confirm('This bill has history. Delete it anyway? Deactivate is safer and preserves history.'))return}else if(!confirm(`Delete ${b.name}?`))return;db.bills=db.bills.filter(x=>x.id!==id);db.billOccurrences=db.billOccurrences.filter(o=>o.billId!==id);save();render()}
function openPaymentModal(occId){ensureBillOccurrences();let o=getOccurrence(occId),b=o&&getBill(o.billId);if(!o||!b)return;let paid=occurrencePaidAmount(o),remaining=Math.max(0,(+o.expectedAmount||0)-paid),todayKey=localDateKey(today);if(occurrenceDisplayStatus(o)==='paid'){showBillOccurrence(occId);return}$('modalTitle').textContent=paid?'Add payment':'Mark bill paid';$('modalForm').innerHTML=`<div class="formgrid">${f('Bill','billName','text',b.name,'readonly')}${f('Payment date','date','date',todayKey,'required')}${f('Actual amount','amount','number',remaining||o.expectedAmount,'required min="0.01" step=".01"')}${f('Payment account','account','text','','placeholder="Checking"')}${s('Category','category',db.categories,b.category||'Other')}${f('Payment note','note')}<div class="full"><div class="notice">Due ${dateText(o.dueDate)} · Expected ${money(o.expectedAmount)} · Already paid ${money(paid)}. This creates one Transaction linked to this bill occurrence.</div></div><div class="full"><button class="btn primary" type="submit">Save payment</button></div></div>`;$('modalForm').dataset.type='payment';$('modalForm').dataset.occurrenceId=occId;$('modalBack').classList.add('show')}
function deleteTransaction(id){let t=db.transactions.find(x=>x.id===id);if(!t)return;if(!confirm('Delete this transaction? If it is linked to a bill, that bill will become unpaid again.'))return;db.transactions=db.transactions.filter(x=>x.id!==id);if(t.billOccurrenceId){let o=getOccurrence(t.billOccurrenceId);if(o){o.payments=(o.payments||[]).filter(x=>x!==id);if(o.transactionId===id)o.transactionId=o.payments?.[0]||null;let remaining=occurrencePaidAmount(o);let remainingPayments=occurrencePayments(o);o.paidDate=remainingPayments.length?remainingPayments[remainingPayments.length-1].date:null;o.actualAmount=remaining||null;o.status=occurrenceDisplayStatus(o)}}save();render()}
function linkTransactionToBill(txId,occId){let t=db.transactions.find(x=>x.id===txId),o=getOccurrence(occId);if(!t||!o)return;if(t.type!=='expense'){alert('Only expense transactions can be linked to a bill.');return}if(occurrenceDisplayStatus(o)==='paid'){alert('This bill occurrence is already fully paid.');return}if(t.billOccurrenceId&&t.billOccurrenceId!==occId){alert('This transaction is already linked to another bill.');return}t.billOccurrenceId=occId;o.payments=o.payments||[];if(!o.payments.includes(txId))o.payments.push(txId);o.transactionId=o.payments[0]||null;o.paidDate=t.date;o.actualAmount=occurrencePaidAmount(o);o.status=occurrenceDisplayStatus(o);save();render()}

function renderBudgets(){let m=currentMonth();$('budgetList').innerHTML=db.budgets.map(b=>{let actual=db.transactions.filter(t=>t.type==='expense'&&t.category===b.category&&t.date.startsWith(m)).reduce((s,t)=>s+ +t.amount,0),p=b.limit?Math.min(100,actual/b.limit*100):0;return `<div class="card"><div class="sectionhead"><b>${esc(b.category)}</b><button class="btn small danger" onclick="remove('budgets','${b.id}')">Delete</button></div><div class="label">${money(actual)} of ${money(b.limit)}</div><div class="progress section"><div class="bar" style="width:${p}%"></div></div><div class="mini section">${p.toFixed(0)}% used</div></div>`}).join('')||'<div class="empty">Create a budget category.</div>'}
function renderDebts(){let bal=db.debts.reduce((s,x)=>s+ +x.balance,0),pay=debtPayments(),interest=db.debts.reduce((s,x)=>s+ +payoff(x).interest,0);$('debtCards').innerHTML=[['Debt balance',money(bal)],['Monthly payment',money(pay)],['Projected interest',money(interest)],['Accounts',db.debts.length]].map(a=>`<div class="card"><div class="label">${a[0]}</div><div class="metric">${a[1]}</div></div>`).join('');$('debtTable').innerHTML=db.debts.map(d=>{let p=payoff(d);return `<tr><td><b>${esc(d.name)}</b><br><span class="mini">${esc(d.type)}</span></td><td>${money(d.balance)}</td><td>${(+d.apr).toFixed(2)}%</td><td>${money(d.minimum)}</td><td>${money(d.extra)}</td><td>${p.date}</td><td>${money(p.interest)}</td><td>${historyButton('debts',d.id)} <button class="btn small danger" onclick="remove('debts','${d.id}')">Delete</button></td></tr>`}).join('')||'<tr><td colspan="8" class="empty">No debts.</td></tr>';canvas('debtChart','line',db.debts.map(d=>({l:d.name.slice(0,9),v:d.balance})));$('strategy').innerHTML=`<div class="notice">Avalanche focuses extra payments on higher APR balances; snowball focuses extra payments on smaller balances. This app records the inputs and payoff math so you can compare them without changing your accounts.</div>`}
function renderGoals(){ $('goalList').innerHTML=db.goals.map(g=>{let p=g.target?Math.min(100,g.saved/g.target*100):0;return `<div class="card"><div class="sectionhead"><b>${esc(g.name)}</b><span>${historyButton('goals',g.id)} <button class="btn small danger" onclick="remove('goals','${g.id}')">Delete</button></span></div><div class="label">${money(g.saved)} of ${money(g.target)}${g.date?' · '+dateText(g.date):''}</div><div class="progress section"><div class="bar" style="width:${p}%"></div></div><div class="split section mini"><span>${p.toFixed(0)}%</span><span>${money(Math.max(0,g.target-g.saved))} remaining</span></div></div>`}).join('')||'<div class="empty">No goals.</div>'}
function renderNetworth(){let a=db.assets.reduce((s,x)=>s+ +x.value,0),l=db.liabilities.reduce((s,x)=>s+ +x.value,0)+db.debts.reduce((s,x)=>s+ +x.balance,0);$('nwCards').innerHTML=[['Assets',money(a)],['Liabilities',money(l)],['Net worth',money(a-l),a-l>=0?'good':'bad'],['Investments',money(db.investments.reduce((s,x)=>s+ +x.balance,0))]].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="metric ${x[2]||''}">${x[1]}</div></div>`).join('');$('assetList').innerHTML=db.assets.map(x=>`<div class="listrow"><span>${esc(x.name)}<br><span class="mini">${esc(x.type)}</span></span><span><b>${money(x.value)}</b> ${historyButton('assets',x.id)} <button class="btn small danger" onclick="remove('assets','${x.id}')">×</button></span></div>`).join('')||'<div class="empty">No assets.</div>';$('liabilityList').innerHTML=db.liabilities.map(x=>`<div class="listrow"><span>${esc(x.name)}<br><span class="mini">${esc(x.type)}</span></span><span><b>${money(x.value)}</b> ${historyButton('liabilities',x.id)} <button class="btn small danger" onclick="remove('liabilities','${x.id}')">×</button></span></div>`).join('')||'<div class="empty">No extra liabilities. Debts are shown in debt payoff.</div>'}
function renderInvestments(){let total=db.investments.reduce((s,x)=>s+ +x.balance,0),monthly=db.investments.reduce((s,x)=>s+ +x.monthly,0);$('invCards').innerHTML=[['Invested balance',money(total)],['Monthly contributions',money(monthly)],['Accounts',db.investments.length]].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="metric">${x[1]}</div></div>`).join('');$('invTable').innerHTML=db.investments.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.type)}</td><td>${money(x.balance)}</td><td>${money(x.monthly)}</td><td>${esc(x.allocation||'Not set')}</td><td>${historyButton('investments',x.id)} <button class="btn small danger" onclick="remove('investments','${x.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No investment accounts.</td></tr>'}
function renderReports(){let p=forecast();$('reportCards').innerHTML=[['12-month income',money(p.reduce((s,x)=>s+x.inc,0))],['12-month outflow',money(p.reduce((s,x)=>s+x.b+x.sp+x.debt+x.gi,0))],['12-month net',money(p.reduce((s,x)=>s+x.net,0))],['Ending cash',money(p[p.length-1]?.cash||0)]].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="metric">${x[1]}</div></div>`).join('');canvas('incomeOutChart','bars',p.map(x=>({l:x.key.slice(5),a:x.inc,b:x.b+x.sp+x.debt+x.gi})));canvas('projectionChart','line',p.map(x=>({l:x.key.slice(5),v:x.cash})));$('forecastTable').innerHTML=p.map(x=>`<tr><td>${x.key}</td><td>${money(x.inc)}</td><td>${money(x.b)}</td><td>${money(x.sp)}</td><td>${money(x.debt)}</td><td>${money(x.gi)}</td><td class="${x.net>=0?'good':'bad'}">${money(x.net)}</td><td>${money(x.cash)}</td></tr>`).join('')}
function yearOf(date){return String(date||'').slice(0,4)}
function annualYears(){let years=new Set([String(today.getFullYear())]);[...db.transactions,...db.paychecks,...db.bills].forEach(x=>{if(x.date)years.add(yearOf(x.date))});return [...years].filter(Boolean).sort().reverse()}
function annualBillAmount(b,y){ensureBillOccurrences();let start=`${y}-01-01`,end=`${y}-12-31`;return db.billOccurrences.filter(o=>o.dueDate>=start&&o.dueDate<=end).reduce((s,o)=>s+(+o.expectedAmount||0),0)}
function annualData(y){let tx=db.transactions,earned=tx.filter(t=>t.type==='income'&&t.date.startsWith(y)).reduce((s,t)=>s+(+t.amount||0),0),spent=tx.filter(t=>t.type==='expense'&&t.date.startsWith(y)).reduce((s,t)=>s+(+t.amount||0),0),expenseCats={},incomeCats={};tx.filter(t=>t.date.startsWith(y)).forEach(t=>{let k=t.category||'Other',a=+t.amount||0;if(t.type==='expense')expenseCats[k]=(expenseCats[k]||0)+a;if(t.type==='income')incomeCats[k]=(incomeCats[k]||0)+a});let quarters=[1,2,3,4].map(q=>{let months=[q*3-2,q*3-1,q*3].map(n=>String(n).padStart(2,'0')),e=tx.filter(t=>t.type==='income'&&months.some(m=>t.date.startsWith(`${y}-${m}`))).reduce((s,t)=>s+(+t.amount||0),0),sp=tx.filter(t=>t.type==='expense'&&months.some(m=>t.date.startsWith(`${y}-${m}`))).reduce((s,t)=>s+(+t.amount||0),0),debt=tx.filter(t=>t.type==='expense'&&(t.category==='Debt Payment'||/debt|loan|credit/i.test(t.category||''))&&months.some(m=>t.date.startsWith(`${y}-${m}`))).reduce((s,t)=>s+(+t.amount||0),0);return{q:`Q${q}`,earned:e,spent:sp,saved:e-sp,rate:e?((e-sp)/e*100):0,debt}});let months=Array.from({length:12},(_,i)=>{let m=String(i+1).padStart(2,'0'),prefix=`${y}-${m}`,e=tx.filter(t=>t.date.startsWith(prefix)&&t.type==='income').reduce((s,t)=>s+(+t.amount||0),0),sp=tx.filter(t=>t.date.startsWith(prefix)&&t.type==='expense').reduce((s,t)=>s+(+t.amount||0),0),debt=tx.filter(t=>t.date.startsWith(prefix)&&t.type==='expense'&&(t.category==='Debt Payment'||/debt|loan|credit/i.test(t.category||''))).reduce((s,t)=>s+(+t.amount||0),0);let bills=db.billOccurrences.filter(o=>o.dueDate.startsWith(prefix)).reduce((s,o)=>s+(+o.expectedAmount||0),0);return{m,label:new Date(+y,i,1).toLocaleDateString(undefined,{month:'short'}),earned:e,spent:sp,net:e-sp,bills,debt}});let bills=db.bills.map(b=>({name:b.name,amount:annualBillAmount(b,y),category:b.category})).filter(x=>x.amount>0).sort((a,b)=>b.amount-a.amount);return{tx,earned,spent,net:earned-spent,expenseCats,incomeCats,months,quarters,bills,totalBills:bills.reduce((s,x)=>s+x.amount,0)}}
function renderAnnual(){
 let years=annualYears(), sel=$('annualYear'), current=String(today.getFullYear());
 if(sel){let old=sel.value;sel.innerHTML=years.map(y=>`<option value="${y}">${y}</option>`).join('');sel.value=years.includes(old)?old:current;}
 let y=sel?.value||current,d=annualData(y),savingRate=d.earned?d.net/d.earned*100:0;
 $('annualCards').innerHTML=[['Earned income',money(d.earned),''],['Actual spending',money(d.spent),''],['Net retained',money(d.net),d.net>=0?'good':'bad'],['Planned annual bills',money(d.totalBills),'']].map(a=>`<div class="card"><div class="label">${a[0]}</div><div class="metric ${a[2]}">${a[1]}</div></div>`).join('');
 $('annualIncomeNote').textContent=`${Object.keys(d.incomeCats).length} income source${Object.keys(d.incomeCats).length===1?'':'s'}`;
 $('annualExpenseNote').textContent=`${Object.keys(d.expenseCats).length} spending categor${Object.keys(d.expenseCats).length===1?'y':'ies'}`;
 canvas('annualIncomeChart','pie',Object.entries(d.incomeCats).sort((a,b)=>b[1]-a[1]).slice(0,7).map(x=>({l:x[0],v:x[1]})));
 canvas('annualExpenseChart','pie',Object.entries(d.expenseCats).sort((a,b)=>b[1]-a[1]).slice(0,7).map(x=>({l:x[0],v:x[1]})));
 canvas('annualBillsChart','bars',d.bills.slice(0,10).map(x=>({l:x.name.slice(0,12),a:x.amount})));
 canvas('annualQuarterChart','bars',d.quarters.map(x=>({l:x.q,a:x.earned,b:x.spent})));
 canvas('annualMonthlyChart','bars',d.months.map(x=>({l:x.label,a:x.earned,b:x.spent})));
 $('annualQuarterTable').innerHTML=d.quarters.map(x=>`<tr><td><b>${x.q}</b></td><td class="good">${money(x.earned)}</td><td class="bad">${money(x.spent)}</td><td class="${x.saved>=0?'good':'bad'}">${money(x.saved)}</td><td>${x.rate.toFixed(1)}%</td><td>${money(x.debt)}</td></tr>`).join('');
 $('annualMonthTable').innerHTML=d.months.map(x=>`<tr><td><b>${x.label}</b></td><td class="good">${money(x.earned)}</td><td class="bad">${money(x.spent)}</td><td class="${x.net>=0?'good':'bad'}">${money(x.net)}</td><td>${money(x.bills)}</td><td>${money(x.debt)}</td></tr>`).join('');
 $('annualDebtList').innerHTML=db.debts.slice().sort((a,b)=>+b.balance-+a.balance).map(x=>{let p=payoff(x);return `<div class="listrow"><span><b>${esc(x.name)}</b><br><span class="mini">${(+x.apr).toFixed(2)}% APR · ${p.date}</span></span><b>${money(x.balance)}</b></div>`}).join('')||'<div class="empty">No debt accounts added.</div>';
}
$('annualYear')?.addEventListener('change',renderAnnual);$('annualThisYear')?.addEventListener('click',()=>{if($('annualYear')){$('annualYear').value=String(today.getFullYear());renderAnnual()}});
function renderData(){$('appVersion').value=APP_VERSION;$('updateLastChecked').value=db.settings.updates?.lastChecked?new Date(db.settings.updates.lastChecked).toLocaleString():'Never';$('autoUpdates').checked=db.settings.updates?.auto!==false;$('updateStatus').textContent='Current';$('currency').value=db.settings.currency;$('startCash').value=db.settings.startingCash;$('saveTarget').value=db.settings.saveTarget;$('incomeGrowth').value=db.settings.incomeGrowth;renderAppearanceSettings();if($('supabaseUrl'))$('supabaseUrl').value=db.settings.sync?.url||'';if($('supabaseKey'))$('supabaseKey').value=db.settings.sync?.key||'';if($('syncEmail'))$('syncEmail').value=db.settings.sync?.email||'';}
function render(){let p=document.querySelector('.page.active')?.id||'dashboard';if(p==='dashboard')renderDashboard();if(p==='annual')renderAnnual();if(p==='plan')renderPlan();if(p==='transactions')renderTransactions();if(p==='bills')renderBills();if(p==='budgets')renderBudgets();if(p==='debts')renderDebts();if(p==='goals')renderGoals();if(p==='networth')renderNetworth();if(p==='investments')renderInvestments();if(p==='reports')renderReports();if(p==='data')renderData()}
function addHistoryEvent(type,id){let item=db[type]?.find(x=>x.id===id);if(!item)return;let valueField=type==='goals'?'saved':type==='investments'?'balance':type==='debts'?'balance':type==='liabilities'||type==='assets'?'value':null;if(!valueField)return;let titleMap={goals:'Savings',investments:'Investment',debts:'Debt',liabilities:'Liability',assets:'Asset'};let value=+item[valueField]||0;let date=localDateKey(today);let body=`<div class="formgrid">${f('Effective date','date','date',date,'required')}${f('Balance / value', 'value','number',value,'required min="0" step=".01"')}<div class="full"><div class="notice">This records a historical point for ${titleMap[type]||'account'}. Use a past date if you know what the balance/value was then.</div></div><div class="full"><button class="btn primary" type="submit">Record history</button></div></div>`;$('modalTitle').textContent=`Record ${titleMap[type]||'balance'} history`;$('modalForm').innerHTML=body;$('modalForm').dataset.type='history';$('modalForm').dataset.historyType=type;$('modalForm').dataset.historyId=id;$('modalBack').classList.add('show')}
function historyButton(type,id){return `<button class="btn small" onclick="addHistoryEvent('${type}','${id}')">History</button>`}
function remove(type,id){db[type]=db[type].filter(x=>x.id!==id);save();render()}

function f(label,name,type='text',value='',extra=''){return `<div class="field"><label>${label}</label><input name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`}
function s(label,name,opts,value=''){return `<div class="field"><label>${label}</label><select name="${name}">${opts.map(o=>`<option value="${esc(o)}" ${o===value?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`}
function unpaidBillOptions(){ensureBillOccurrences();return db.billOccurrences.filter(o=>occurrenceDisplayStatus(o)!=='paid').sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,150)}
function refreshBillFormVisibility(){let form=$('modalForm');if(!form||!['bill','billEdit'].includes(form.dataset.type))return;let bt=form.querySelector('[name="billType"]')?.value,at=form.querySelector('[name="amountType"]')?.value;let freq=form.querySelector('[name="frequency"]')?.closest('.field');if(freq)freq.style.display=bt==='one-time'?'none':'';let notice=form.querySelector('.notice');if(notice)notice.textContent=at==='variable'?'Expected amount is a planning estimate. The actual payment amount is recorded when the bill is paid.':'Fixed bills still allow the actual payment amount to be edited when paid. Changes to an existing bill apply to future unpaid occurrences; paid history and transactions stay unchanged.'}
function closeModal(){
  const back=$('modalBack');
  const form=$('modalForm');
  if(back)back.classList.remove('show');
  if(form){form.reset?.();form.innerHTML='';delete form.dataset.type;delete form.dataset.editId;delete form.dataset.occurrenceId;delete form.dataset.historyType;delete form.dataset.historyId;}
  if($('modalTitle'))$('modalTitle').textContent='';
}
window.closeModal=closeModal;
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('modalBack')?.classList.contains('show'))closeModal()});

function openModal(type,preset=null){let title='',body='';
if(type==='transaction'){title='Add transaction';body=`<div class="formgrid">${f('Date','date','date',iso(today),'required')}${s('Type','type',['expense','income','transfer'],'expense')}${f('Payee / merchant','payee','text','','required placeholder="e.g. Publix"')}${f('Amount','amount','number','','required min="0" step=".01"')}${s('Category','category',db.categories,'Other')}${f('Account','account','text','','placeholder="Checking"')}${f('Note','note')}${f('Clears on','clears','date','')}<div class="field"><label>Link to bill</label><select name="billOccurrenceId"><option value="">None</option>${unpaidBillOptions().map(o=>{let b=getBill(o.billId);return `<option value="${o.id}">${esc(b?.name||'Bill')} — ${dateText(o.dueDate)}</option>`}).join('')}</select></div><div class="full mini">Linking an existing transaction to a bill marks that bill occurrence paid; it does not create another charge.</div><div class="full"><button class="btn primary" type="submit">Save</button></div></div>`}
if(type==='bill'||type==='billEdit'){let b=preset||{};title=type==='billEdit'?'Edit Bill':'Add Bill';let freq=b.frequency||'monthly',bt=b.billType||'recurring',at=b.amountType||'fixed';body=`<div class="formgrid"><div class="full"><h3 style="margin:0">Basic Information</h3></div>${f('Bill name','name','text',b.name||'','required placeholder="Rent"')}${s('Category','category',db.categories,b.category||'Housing')}${s('Bill type','billType',['recurring','one-time'],bt)}<div class="full"><h3 style="margin:8px 0 0">Amount</h3></div>${s('Amount type','amountType',['fixed','variable'],at)}${f('Expected amount','expectedAmount','number',b.expectedAmount??b.amount??'','required min="0" step=".01"')}<div class="full"><h3 style="margin:8px 0 0">Schedule</h3></div>${f('First due date','startDate','date',b.startDate||iso(today),'required')}${s('Frequency','frequency',['weekly','biweekly','monthly','quarterly','semiannual','annual'],freq)}<div class="full"><h3 style="margin:8px 0 0">Payment</h3></div>${s('Autopay','autopay',['no','yes'],b.autopay?'yes':'no')}${f('Notes','notes','text',b.notes||'','placeholder="Optional bill notes"')}${type==='billEdit'?`${s('Status','active',['active','inactive'],b.active===false?'inactive':'active')}`:''}<div class="full"><div class="notice">${at==='variable'?'Expected amount is a planning estimate. The actual payment amount is recorded when the bill is paid.':'Fixed bills still allow the actual payment amount to be edited when paid.'} Changes to an existing bill apply to future unpaid occurrences; paid history and transactions stay unchanged.</div></div><div class="full"><button class="btn primary" type="submit">${type==='billEdit'?'Save Changes':'Create Bill'}</button></div></div>`}
if(type==='paycheck'){title='Add paycheck';body=`<div class="formgrid">${f('Pay date','date','date',iso(today),'required')}${f('Name','name','','','placeholder="City paycheck"')}${f('Amount','amount','number','','required min="0" step=".01"')}${s('Frequency','frequency',['one-time','weekly','biweekly','semi-monthly','monthly'],'biweekly')}<div class="full"><button class="btn primary" type="submit">Save paycheck</button></div></div>`}
if(type==='assignment'){title='Assign paycheck money';body=`<div class="formgrid">${s('Paycheck','paycheckId',db.paychecks.map(p=>p.id),db.paychecks[0]?.id||'')}${f('Envelope / bill','envelope','','','required placeholder="Rent"')}${f('Amount','amount','number','','required min="0" step=".01"')}${f('Note','note')}<div class="full"><button class="btn primary" type="submit">Assign</button></div></div>`}
if(type==='budget'){title='Create monthly budget';body=`<div class="formgrid">${s('Category','category',db.categories,'Groceries')}${f('Monthly limit','limit','number','','required min="0" step=".01"')}<div class="full"><button class="btn primary" type="submit">Save budget</button></div></div>`}
if(type==='debt'){title='Add debt';body=`<div class="formgrid">${f('Debt name','name','','','required')}${s('Type','type',['Credit Card','Auto Loan','Personal Loan','Student Loan','Mortgage','Medical','Other'],'Other')}${f('Balance','balance','number','','required min="0" step=".01"')}${f('APR %','apr','number','','required min="0" step=".01"')}${f('Minimum payment','minimum','number','','required min="0" step=".01"')}${f('Extra payment','extra','number','0','min="0" step=".01"')}<div class="full"><button class="btn primary" type="submit">Save debt</button></div></div>`}
if(type==='goal'){title='Create savings goal';body=`<div class="formgrid">${f('Goal name','name','','','required')}${f('Target amount','target','number','','required min="0" step=".01"')}${f('Current saved','saved','number','0','min="0" step=".01"')}${f('Target date','date','date','')}<div class="full"><button class="btn primary" type="submit">Create goal</button></div></div>`}
if(type==='asset'){title='Add asset';body=`<div class="formgrid">${f('Name','name','','','required')}${s('Type','type',['Cash','Vehicle','Property','Retirement','Brokerage','Other'],'Cash')}${f('Current value','value','number','','required min="0" step=".01"')}<div class="full"><button class="btn primary" type="submit">Save asset</button></div></div>`}
if(type==='liability'){title='Add liability';body=`<div class="formgrid">${f('Name','name','','','required')}${s('Type','type',['Credit Card','Loan','Mortgage','Medical','Other'],'Other')}${f('Current balance','value','number','','required min="0" step=".01"')}<div class="full"><button class="btn primary" type="submit">Save liability</button></div></div>`}
if(type==='investment'){title='Add investment account';body=`<div class="formgrid">${f('Account name','name','','','required')}${s('Type','type',['Roth IRA','401(k)','403(b)','Brokerage','HSA','Other'],'Roth IRA')}${f('Current balance','balance','number','','required min="0" step=".01"')}${f('Monthly contribution','monthly','number','0','min="0" step=".01"')}${f('Allocation','allocation','text','','placeholder="70% VOO / 20% VXUS / 10% BND"')}<div class="full"><button class="btn primary" type="submit">Save account</button></div></div>`}
$('modalTitle').textContent=title;$('modalForm').innerHTML=body;$('modalForm').dataset.type=type;if(preset)$('modalForm').dataset.editId=preset.id;$('modalBack').classList.add('show');if(type==='bill'||type==='billEdit'){refreshBillFormVisibility();$('modalForm').querySelector('[name=\"billType\"]')?.addEventListener('change',refreshBillFormVisibility);$('modalForm').querySelector('[name=\"amountType\"]')?.addEventListener('change',refreshBillFormVisibility)}}
$('modalBack').onclick=e=>{if(e.target===$('modalBack'))closeModal()};
$('modalForm').onsubmit=e=>{e.preventDefault();let t=e.target.dataset.type,o=Object.fromEntries(new FormData(e.target).entries());
 if(t==='payment'){let occ=getOccurrence(e.target.dataset.occurrenceId),b=occ&&getBill(occ.billId);if(!occ||!b)return;let amt=+o.amount;if(!Number.isFinite(amt)||amt<=0)return alert('Enter a valid payment amount.');let tx={id:uid(),date:o.date,type:'expense',payee:b.name,amount:amt,category:o.category||b.category||'Other',account:o.account||'',note:o.note||'',billOccurrenceId:occ.id};db.transactions.push(tx);occ.payments=occ.payments||[];occ.payments.push(tx.id);occ.transactionId=occ.payments[0];occ.paidDate=o.date;occ.actualAmount=occurrencePaidAmount(occ);occ.status=occurrenceDisplayStatus(occ);save();closeModal();render();showBillOccurrence(occ.id);return}
 if(t==='history'){let type=e.target.dataset.historyType,id=e.target.dataset.historyId,item=db[type]?.find(x=>x.id===id);if(!item)return;let field=type==='goals'?'saved':type==='investments'||type==='debts'?'balance':'value';let date=String(o.date||''),value=+o.value;if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(value)||value<0){alert('Enter a valid date and non-negative value.');return}item.history=Array.isArray(item.history)?item.history:[];item.history=item.history.filter(h=>h.date!==date);item.history.push({date,value});item.history.sort((a,b)=>a.date.localeCompare(b.date));if(date===iso(today))item[field]=value;save();closeModal();render();return}
 if(t==='bill'||t==='billEdit'){let id=e.target.dataset.editId||uid();let old=getBill(id),bill={id,name:String(o.name||'').trim(),category:o.category,billType:o.billType,amountType:o.amountType,expectedAmount:+o.expectedAmount,frequency:o.billType==='one-time'?'monthly':o.frequency,startDate:o.startDate,autopay:o.autopay==='yes',notes:o.notes||'',active:t==='billEdit'?o.active==='active':true,createdAt:old?.createdAt||iso(today)};if(!bill.name||!bill.startDate||!Number.isFinite(bill.expectedAmount)||bill.expectedAmount<0){alert('Complete the required bill fields.');return}if(t==='bill'){db.bills.push(bill)}else{Object.assign(old,bill);db.billOccurrences=db.billOccurrences.filter(x=>x.billId!==id||['paid','partial'].includes(occurrenceDisplayStatus(x)));}ensureBillOccurrences();save();closeModal();render();return}
 o.id=uid();if(t==='transaction'){o.amount=+o.amount;let bo=o.billOccurrenceId;delete o.billName;delete o.billOccurrenceId;db.transactions.push(o);if(bo){let occ=getOccurrence(bo);if(occ){o.billOccurrenceId=bo;occ.payments=occ.payments||[];if(!occ.payments.includes(o.id))occ.payments.push(o.id);occ.transactionId=occ.payments[0]||null;occ.paidDate=o.date;occ.actualAmount=occurrencePaidAmount(occ);occ.status=occurrenceDisplayStatus(occ)}}}
if(t==='paycheck'){o.amount=+o.amount;db.paychecks.push(o)}if(t==='assignment'){o.amount=+o.amount;db.assignments.push(o)}if(t==='budget'){o.limit=+o.limit;db.budgets.push(o)}if(t==='debt'){o.balance=+o.balance;o.apr=+o.apr;o.minimum=+o.minimum;o.extra=+o.extra;o.createdAt=iso(today);o.history=[{date:o.createdAt,value:o.balance}];db.debts.push(o)}if(t==='goal'){o.target=+o.target;o.saved=+o.saved;o.createdAt=iso(today);o.history=[{date:o.createdAt,value:o.saved}];db.goals.push(o)}if(t==='asset'){o.value=+o.value;o.createdAt=iso(today);o.history=[{date:o.createdAt,value:o.value}];db.assets.push(o)}if(t==='liability'){o.value=+o.value;o.createdAt=iso(today);o.history=[{date:o.createdAt,value:o.value}];db.liabilities.push(o)}if(t==='investment'){o.balance=+o.balance;o.monthly=+o.monthly;o.createdAt=iso(today);o.history=[{date:o.createdAt,value:o.balance}];db.investments.push(o)}save();closeModal();render()};
$('saveSettings').onclick=()=>{db.settings.currency=$('currency').value;db.settings.startingCash=+$('startCash').value||0;db.settings.saveTarget=+$('saveTarget').value||0;db.settings.incomeGrowth=+$('incomeGrowth').value||0;db.settings.appearance.density=$('density').value;if(accentTouched)db.settings.appearance.customAccent=$('customAccent').value;save();applyAppearance();render()};
$('exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='personal-budget-backup-'+iso(today)+'.json';a.click()};
$('importBtn').onclick=()=>$('fileInput').click();
async function checkForUpdates(){let status=$('updateStatus');status.textContent='Checking…';try{let r=await fetch('./version.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('Version check failed');let v=await r.json();db.settings.updates.lastChecked=new Date().toISOString();save();$('updateLastChecked').value=new Date(db.settings.updates.lastChecked).toLocaleString();if(v.version&&v.version!==APP_VERSION){status.textContent='Update available';$('updateWhatsNew').textContent=v.whatsNew||'A newer Budget OS version is available. Reload the app to apply it.'}else{status.textContent='Current';$('updateWhatsNew').textContent='You are using the latest version.'} }catch(e){status.textContent='Check unavailable';$('updateWhatsNew').textContent='The app could not reach the update check. The app can still work normally offline.'}}
$('checkUpdates')?.addEventListener('click',checkForUpdates);$('autoUpdates')?.addEventListener('change',e=>{db.settings.updates.auto=e.target.checked;save()});
$('fileInput').onchange=e=>{let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.settings||!x.categories)throw 1;db=x;save();render();alert('Backup restored.')}catch{alert('Invalid backup file.')}};r.readAsText(file)};
$('csvBtn').onclick=()=>{let rows=[['Date','Payee','Type','Category','Account','Amount','Note'],...db.transactions.map(x=>[x.date,x.payee,x.type,x.category,x.account,x.amount,x.note])];let csv=rows.map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='transactions.csv';a.click()};
$('eraseBtn').onclick=()=>{if(confirm('Erase all data? Export a backup first if you may need it.')){localStorage.removeItem(KEY);localStorage.removeItem(LEGACY_KEY);location.reload()}};

let supabaseClient=null;
async function loadSupabase(){
  if(supabaseClient)return supabaseClient;
  let url=(db.settings.sync?.url||'').trim(), key=(db.settings.sync?.key||'').trim();
  if(!url||!key)throw new Error('Add your Supabase project URL and publishable key first.');
  if(!/^https:\/\/[^\s]+$/.test(url))throw new Error('Supabase URL must start with https:// and be your project URL.');
  let mod=await import('https://esm.sh/@supabase/supabase-js@2');
  supabaseClient=mod.createClient(url,key,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:false}});
  return supabaseClient;
}
function syncMessage(msg,ok=false){if($('syncStatus'))$('syncStatus').textContent=msg;if($('syncDot'))$('syncDot').className='statusDot '+(ok?'ok':'');}
async function getSignedInUser(){
  let c=await loadSupabase();
  let {data,error}=await c.auth.getSession();
  if(error)throw error;
  return data?.session?.user||null;
}
async function syncConnect(){
  try{
    db.settings.sync.url=$('supabaseUrl').value.trim();
    db.settings.sync.key=$('supabaseKey').value.trim();
    db.settings.sync.email=$('syncEmail').value.trim();
    save();
    if(!db.settings.sync.email)throw new Error('Enter the Budget OS account email.');
    if(!$('syncPassword').value)throw new Error('Enter the Budget OS account password.');
    let c=await loadSupabase();
    syncMessage('Signing in to Supabase…',true);
    let {data,error}=await c.auth.signInWithPassword({email:db.settings.sync.email,password:$('syncPassword').value});
    if(error)throw error;
    if(!data?.session||!data?.user)throw new Error('Supabase accepted the login but did not return an active session.');
    let check=await c.auth.getSession();
    if(check.error)throw check.error;
    if(!check.data.session)throw new Error('Sign-in completed but no browser session was stored.');
    syncMessage('Connected — signed in as '+(data.user.email||db.settings.sync.email)+'. Upload or download is ready.',true);
  }catch(e){
    console.error('Budget OS cloud sync connection error',e);
    syncMessage('Connection failed: '+(e.message||e),false);
    alert('Cloud sync connection failed: '+(e.message||e));
  }
}
async function syncPush(){
  try{
    let c=await loadSupabase(), user=await getSignedInUser();
    if(!user)throw new Error('This device is not signed in. Click Connect first.');
    let {error}=await c.from('budget_os_data').upsert({user_id:user.id,data:db,updated_at:new Date().toISOString()},{onConflict:'user_id'});
    if(error)throw error;
    syncMessage('Cloud backup updated just now.',true);
  }catch(e){
    console.error('Budget OS cloud upload error',e);
    syncMessage('Upload failed: '+(e.message||e),false);
    alert('Upload failed: '+(e.message||e));
  }
}
async function syncPull(){
  try{
    let c=await loadSupabase(), user=await getSignedInUser();
    if(!user)throw new Error('This device is not signed in. Click Connect first.');
    let {data,error}=await c.from('budget_os_data').select('data,updated_at').eq('user_id',user.id).maybeSingle();
    if(error)throw error;
    if(!data){syncMessage('Signed in. No cloud copy exists yet — upload this device first.',true);return;}
    if(confirm('Replace this device with the cloud copy? Export a backup first if unsure.')){db=data.data;save();applyAppearance();render();}
    syncMessage('Cloud data downloaded just now.',true);
  }catch(e){
    console.error('Budget OS cloud download error',e);
    syncMessage('Download failed: '+(e.message||e),false);
    alert('Download failed: '+(e.message||e));
  }
}
async function syncSignOut(){try{let c=await loadSupabase();await c.auth.signOut();syncMessage('Signed out.',true);}catch(e){syncMessage('Sign out failed: '+(e.message||e),false);}}
$('syncConnect')?.addEventListener('click',syncConnect);
$('syncPush')?.addEventListener('click',syncPush);
$('syncPull')?.addEventListener('click',syncPull);
$('syncSignOut')?.addEventListener('click',syncSignOut);
let syncTimer=null;window.addEventListener('pbos-data-changed',()=>{if(db?.settings?.sync?.url&&db?.settings?.sync?.key&&supabaseClient){clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncPush().catch(()=>{}),1200);}});
if($('syncPush'))$('syncPush').disabled=false;if($('syncPull'))$('syncPull').disabled=false;


window.addEventListener('resize',()=>render());
applyAppearance();nav('dashboard');

if('serviceWorker' in navigator){
  window.addEventListener('load',()=>{navigator.serviceWorker.register('./sw.js').catch(()=>{});if(db.settings.updates?.auto!==false)setTimeout(checkForUpdates,1200)});
}
